<a href="https://colab.research.google.com/github/YokoyamaLab/PythonBasics/blob/main/day01_02LiteralVariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day1-02: リテラルと変数

## 🌀コメント

まず最初にコメントの文法を知っておきましょう。コメントはプログラム中に、実行とは関係のない文章を含める方法で、コードのちょっとした説明等を書きこんでおくのに便利です。C系の言語、例えばJavaやC#はコメントとして```//```を用いますが、Pythonでは```#```を使います。これはRubyやPerlやShellスクリプトと同じ方法です。Webアプリケーションの実装でよく使われるPHPでは```//```と```#```が両方使えます。なおPythonでは複数行にまたがったコメントを書く```/* コメント */```に相当するものはありません。各行の先頭に```#```を各必要があります。



In [ ]:
# ここに書かれている事はプログラムの実行とは何も関係ありません
i = 1 + 1 # プログラムの任意のコードに続けてコメントを書く事も可能です。
print(i) # これは変数iを出力する命令です。このセルを実行すると2が表示されるはずです。

2


## 🌀リテラル

> リテラル・直値（英: literal）は、「文字どおり」「字義どおり」を意味する語で、letter と同じくラテン語の littera（文字）に由来する

> リテラルとは、数理論理学において、原子論理式あるいは原子論理式の否定のこと。

※引用：Wikipedia「[リテラル](https://ja.wikipedia.org/wiki/%E3%83%AA%E3%83%86%E3%83%A9%E3%83%AB)」

Pythonの文法に入る前に、Pythonでは「値(リテラル)」をどのように表すのかを見てみましょう。



### 💮なんにも無い事を表す特殊な定数 ###



なんにも無い事を表す特殊な定数というと何のことか想像がつかないかもしれません。では、貴方が温度センサーを使ったアプリケーションを作っているとしましょう。温度センサーの値(気温=数値)をどこか変数として格納します。その時、変数を定義して、センサデータの値を、例えば一秒に一回等の頻度で更新していきます。そのとき、変数を定義する時点で、どんな初期値をその変数に割り当てるのが良いでしょうか？

最初だから一応「```0```」という人がいるかもしれません。でも```0```は0度を表す數です。たまたまその時刻に0度だったという奇跡が無い限り、この初期値は間違った値を示しています。そんな時に便利な値がこの「なんにも無い事を表す特殊な定数」です。

```
None
```

JavaやCを始めとして殆どの言語で```null```や```NULL```として表されますが、Pythonは```None```を使います。これは意外と様々な所で出現しますが、この時点では「何も無いを表す必要がある」とだけ覚えておいてください。



### 💮ブール値 ###

ブール値とはTrue(真)もしくはFalse(偽)の値の事です。コンピュータが0か1で表された二進数で動いている事は知っていると思いますが、まさしく「1 bit」とは0か１、すなわち```True```か```False```の事です。

```
True
False
```

### 💮文字列 ###


例えばブール値ではなく単なる文字列としてのTrueを表す時、プログラム上で単に```True```と書いてしまっては、それがブール値なのか文字列なのかコンピュータは理解する事ができません。そこで殆どの言語では文字列はブラケット(Bracket)で囲う事になっています。Pythonではシングルコーテーション(```'```)かダブルコーテーション(```"```)で囲います。

```
'Hello World'
"Hello World"
```

```'```と```"```はどちらを使っても殆ど同じです。ただし、一点だけ注意する事があります。例えば以下の文を表示するプログラムを考えてみましょう。

> I'm a student at Tsuda University.

そこで、以下の様なコードを実装してみました。

In [ ]:
print('I'm a student at Tsuda Unibersity')

SyntaxError: ignored

このコードを実行すると**SyntaxError**というエラーが出てくると思います。なぜでしょうか？

**I'm**の**m**の所でエラーがでいますから、おそらくアポストロフィーの問題だと予想がつきます。インタープリタは```'I'm a student...'```最初の**'**の出現で、「ほうほう次の文字からは文字列として解釈すれば良いんだな」と身構えます。そして**I**を読みこみ、その次の文字は**'**ですので、「よし、文字列はここまで！」となります、そして次に**m**が読み込まれて・・・「ん？これはなんだ？」となってしまいます。

このような事態を回避するには二つ方法があります。

1.   ダブルコーテーション(```"```)を使う
2.   エスケープシーケンスを使う

当然ですが文字列をダブルコーテーションで括れば、このような問題は起きません。試してみましょう。


In [ ]:
print("I'm a student at Tsuda University.")

I'm a student at Tsuda University.


エラー無くでてきましたね？

もう一つの**エスケープシーケンス**とは何でしょうか。これは「**次に続く文字(あるいは数字列)は私とセットで解釈してね！**」という特殊な文字列の事で、Pythonでは(そしてJavaやJavaScriptなど多くの言語で)、```\```が使われます。説明だけだと分からないと思いますので、試してみましょう。

In [ ]:
print('I\'m a student at Tsuda University.')

I'm a student at Tsuda University.


文字列の括りにシングルコーテーションを使っていますが、エラー無く動作しました。これは```\'```が「**ここでシングルコーテーションが出てくるけれど、これは文字列の終わりを意味するのではなくて、文字列の一部としての記号だからね**」という意味で解釈されます。

エスケープシーケンスの使い道は他にも色々とありますが、注意点もあります。例えば、皆さんがオンラインショッピングサイトの実装をしたとしましょう。ある商品を13万4千円で販売しようと思い、その価格を表示するために以下のプログラムを作ったとします。では、これを実行してみましょう。

In [ ]:
print('\134000-')

\000-


なんと「0円」と出てきてしまいました。これでは良くて始末書、悪くて解雇ですね。

なぜこんな事が起こったのでしょうか。

実は```\```に続く数字の列はASCIIコードとして解釈するというエスケープシーケンスのルールがあったからです。コンピュータは文字をビットパターン(0と1の列)として符号化します。符号化のルールは世界的な取り決めがあり、最も基本となるのがASCII (American Standard Code for Information Interchange)と呼ばれる一つの文字を7bitで表す符号化方式です。Pythonでは```\```に続いて数字が三文字続いた場合、それを八進数で表された7bit ASCIIコードとして解釈します。

この現象を理解するために、ASCIIコードの日本版の規格**JIS X 0201**を使って説明します。Wikipediaの『JIS X 0201』の項目に[ASCIIコード表](https://ja.wikipedia.org/wiki/JIS_X_0201#%E3%83%A9%E3%83%86%E3%83%B3%E6%96%87%E5%AD%97%E7%94%A8%E5%9B%B3%E5%BD%A2%E6%96%87%E5%AD%97%E9%9B%86%E5%90%88)があるので見てみましょう。(リンクは**Ctrl**キーあるいは**Command**キーを押しながらクリックすると**別のタブ**として開きます)

この表には八進表現が書いていないので八進数**134**の十六進表現である**5C**で調べてみると、```\```である事が分かります。つまり```\134000-```という文字列の最初の4文字```\134```は八進ASCIIで円マーク```\```と解釈されてしまい、結果として```\000-```になっていたのでした。

ここで疑問が沸きます。円マークを表示したい場合は一体全体どうやったら良いのでしょうか。

実は、これもエスケープシーケンスを使います。エスケープシーケンスとしての```\```ではなく、文字としての```\```を表すためには、```\\```と書きます。やってみましょう。

In [ ]:
print('\\134000-')

\134000-


これなら解雇されずに済みます。

他にも便利なエスケープシーケンスがありますので覚えて置きましょう。

In [ ]:
# タブを表す \t
print('Column1\tColumn2')

Column1	Column2


In [ ]:
# 改行を表す \n
print("line1\nline2")

line1
line2


**なぜエスケープシーケンスを表す最初の文字がなぜ円マーク(```\```)なのか**について、最後に少しだけ触れておきます。

エスケープシーケンスは[英語版のWikipedia](https://en.wikipedia.org/wiki/Escape_sequence)を見ると次のような説明があります。

> In C and many derivative programming languages, a string escape sequence is a series of two or more characters, starting with a backslash ```\```.

ここには明確にエスケープシーケンスは**バックスラッシュで始まる**と書かれています。一方で、私達の知っているバックスラッシュは```\```ではなく、**\**ではないでしょうか？

これには歴史的な深い訳があります。[ASCII表](https://ja.wikipedia.org/wiki/ASCII)はアメリカで作られたものですので```$```マークは入っていますが```\```は元々存在しません。もちろん1970年代の事ですから、```€```もありません。ASCII表は英語を表すためだけに作られたものですので、日本語はおろかフランス語も表す事が出来ませんでした。

そこでこのASCIIを世界標準にするために[ISO/IEC 646](https://ja.wikipedia.org/wiki/ISO/IEC_646#%E7%AC%A6%E5%8F%B7%E8%A1%A8)が生まれました。これはASCII表の記号部分の一部を、未定義として、各国が勝手に定義してよいようにしたものです。問題の**0x5C**はまさに未定義(各国が勝手に定義して良い)の部分で、フランスはここに```ç```を割り当て、日本はここに```\```を割り当てた訳です。Comme ça?

その後、ヨーロッパ諸言語は[ISO/IEC 8859](https://ja.wikipedia.org/wiki/ISO/IEC_8859)という規格において、[ダイアクリティカルマーク](https://ja.wikipedia.org/wiki/%E3%83%80%E3%82%A4%E3%82%A2%E3%82%AF%E3%83%AA%E3%83%86%E3%82%A3%E3%82%AB%E3%83%AB%E3%83%9E%E3%83%BC%E3%82%AF)を整理したのですが、```\```は日本以外と整合性のとれないまま、現在に至っています。

なお、現在はASCIIとも互角性のある[Unicode表](https://ja.wikipedia.org/wiki/Unicode)とそれを元にした[UTF-8](https://ja.wikipedia.org/wiki/UTF-8)が主流で、PythonもデフォルトでUnicodeで文字列を管理しています。

Unicodeは世界中のありとあらゆる文字を表現できるようにするプロジェクトで、それ以前は言語ごとにコード体系が異なっており、例えば日本語と韓国語を混ぜたような文書は作る事が出来ませんでした。Unicodeには漢字もハングルも、そして絵文字さえも一つのUnicode表に含まれていますので、こんな事が出来ます。

In [ ]:
print('こんにちは\n안녕하세요\nආයුබෝවන්\nسلام\nவணக்கம்')

こんにちは
안녕하세요
ආයුබෝවන්
سلام
வணக்கம்


上から、日本語、韓国語、シンハラ語、ペルシア語、タミル語です。ペルシア語は右から左に読みます。

複数行の文字列をエスケープシーケンス```\n```を使えば一行で書ける事は分かりましたが、複数行でソースコード中に書く事もできます。以下の例を見てください。

In [ ]:
print('''こんにちは
안녕하세요
ආයුබෝවන්
سلام
வணக்கம்
''')

こんにちは
안녕하세요
ආයුබෝවන්
سلام
வணக்கம்



この方法は**ビアドキュメント**と呼ばれたりします。

さて、文字列はここまで、次に数値を表す方法を学びましょう。

### 💮数値 ###

コンピュータの日本語訳が「***電子計算機***」である事からも想像がつきますが、プログラミングが何のために生まれたかというと、数値を計算するためです。当然Pythonでも数値を扱うことができます。Pythonでは整数値と小数値、そして複素数を扱う事ができます。

#### 整数 ####


```
1234
```

殆どの言語でソースコード中に数字をそのまま書けば、それは整数として解釈されます。例えば上記の例では千二百三十四を表します。ただ、実は厳密にいうと**ただの整数**ではなく、**十進数の整数**としてプログラムは扱っています。コンピュータ自体は2進数で動いていますので、二進法や十六進法で數を扱う事も多いです。またコンピュータではかつて一文字を6bit(八進法二桁)で表していた事もあり、歴史的な経緯で八進法も使われます。十進法の数値と区別するために、リテラルは以下の様に表現します。


In [ ]:
# 十進法
print(51966)

# 二進法
print(0b1100101011111110)

# 八進法
print(0o145376)

# 十六進法
print(0xCAFE)

51966
51966
51966
51966


どうですか？全て**51966**が表示されましたか？

インタープリタが区別できるように、十進法以外では特別な接頭辞が付きます。二進法(Binary number system)の場合は```0b```、八進法(Octal number system)の場合は```0o```、十六進法(Hexadecimal number system)の場合は```0x```を数値の先頭に付けます。

では、それ以外のN進法はどうでしょうか。それを実現するためにPythonでは```int(N, base=B)```という関数が準備されています。これは```N```という文字列を```B```進法で解釈して数値化するという意味の関数で、最大で36進法まで表現できます。では**143I**を**三十六進法**で解釈して表示してみましょう。

In [ ]:
print(int("143I",base=36))

51966


やはりこれも**51966**になりました。上記のコードは皆さんの手元で編集可能ですので、数値を変えて試してみる事も可能です。（この講義では出てくるプログラム例は、ぜひ講義を聴きながら、適当に改変してみて実行しなおしてみる事をお勧めします。自分で少しでも改造すれば、Pythonの文法が頭に入りやすくなります。）

#### 小数 ####

プログラムで扱う数値は整数だけではありません、当然、小数の値も扱えなければなりません。小数の値も整数とおなじく、プログラム内で記述する事ができます。以下のセルを実行してみましょう。

In [ ]:
print(123.45)
print(12345e-2)

123.45
123.45


書き方は二種類あり、前者の```123.45```のようにそのまま小数値を書く方法と、『有効数字』と親和性の高い後者の方法があります。ちなみに後者は以下の式で示される小数値の事で、```123.45```を表します。

$$
12345 \times 10^{-2}
$$

では、次の例はどうでしょうか。

In [ ]:
print(0.1)
print(0.10000000000000001)
print(0.1000000000000000055511151231257827021181583404541015625)

0.1
0.1
0.1


あれ？異なった小数値を表示しようとしているのに、全部が**0.1**になってしまいました。なんででしょう。

実は、コンピュータは、一件数値計算が得意なような顔をしていますが、0.1という簡単な小数値すら、まともに理解する事ができません。

コンピュータはあらゆる値を二進数で管理しています。これが小数値の扱いに問題を引き起こします。どういう事かと言うと、十進数の**0.1**はすなわち「10分の1」を意味しますが、この「10分の1」が二進数では巡回小数になってしまうのです。

> 0.0001100110011001100110011001100110011001100110011...

プログラミング言語では小数の値を[浮動小数点数](https://ja.wikipedia.org/wiki/%E6%B5%AE%E5%8B%95%E5%B0%8F%E6%95%B0%E7%82%B9%E6%95%B0)として管理します。巡回小数の場合、コンピュータのメモリは無限ではないので、ある程度の桁数までしか表せません。Pythonを含む殆どの言語で64bitを使って表します。これを[倍精度浮動小数点数](https://ja.wikipedia.org/wiki/%E5%80%8D%E7%B2%BE%E5%BA%A6%E6%B5%AE%E5%8B%95%E5%B0%8F%E6%95%B0%E7%82%B9%E6%95%B0)と言います。浮動小数点数とは、あらゆる小数を以下のような式で表します。

$$
-123\times 2^{-45}
$$

もちろん**-123**の部分と**-45**の部分は可変です。ここを変える事によって二進法で表す事のできる小数値を表現します。倍精度浮動小数点では、これを64bitで表すのですが、当然長さに限界があります。0.1は巡回小数になる事は説明しましたが、64bitの概数では次の様に表されます。

$$
3602879701896397 \times 2^{-55}
$$

この値は厳密に計算すると```0.1000000000000000055511151231257827021181583404541015625```なのですが、これをPythonでは(そして多くのプログラミング言語でも)```0.1```と表示します。なので、冒頭で示した例の様になるのです。

長々と説明しましたが、簡単に言うと**十進法で示せて当たり前の数が二進法では示せない**という事を常に心の片隅に置いておきましょうという事です。

これ以上は詳しく説明しませんが、以下のような事も起きます。オソロシヤ。

In [ ]:
# 0.1を三回足す
print(0.1+0.1+0.1)

# 0.1を10倍しそれを三回足した後で10で割る
print((0.1 * 10 + 0.1 * 10 + 0.1 * 10) / 10)

0.30000000000000004
0.3


#### 複素数 ####

Pythonでは複素数の値も扱えます。これは単に```2+8j```等と書くだけです。

In [ ]:
print((2 + 8j) * (2 + 8j))

(-60+32j)


ただし、これまでに紹介した実数を前提とした整数型・小数型から複素数へ自由に行き来できる訳では無い事は注意してください。例えば以下のセルを実行してみましょう。Pythonで平方根は```math.sqrt(N)```という関数で求めます。なので、以下の式は数学的な知識があれば、答えは```5i```になる予想が付くと思います。

In [ ]:
print(math.sqrt(-25))

ValueError: ignored

エラーが出てきたと思います。```math.sqrt(N)```が複素数に対応していないためにこのエラーが引き起こされます。幸いPythonには高度な数値計算の為のライブラリが豊富に用意されており、**numpy**というライブラリを利用すると、答えが複素数になるような平方根を計算する事ができます。

In [ ]:
import numpy
numpy.lib.scimath.sqrt(-25)

5j

答えは**5j**とでてきました。もしかしたら皆さんは虚数単位を**i**と習ったかもしれませんが、Pythonでは**j**としています。これは電気系の勉強をしている人にはお馴染みですが、それ以外の人には少々驚きかもしれません。

Pythonを初めてすぐに複素数の扱いが必要になる事は無いとは思いますが、複素数を扱う時は『ライブラリを選ぶ』と覚えておきましょう。

## 🌀変数 ##

### 💮変数定義とデータ型 ###

ここまでリテラルを学んできましたが、リテラルは大抵変数に代入して利用するので、変数の定義の仕方も覚えてしまいましょう。

In [ ]:
name = '津田梅子'
print(name)

津田梅子


これまでにJava等の言語を習得してきた人にとってはすこし拍子抜けするのではないでしょうか。


```
String name = "津田梅子";
```

Javaの場合はこのように変数の型を定義しなくてはならなかったと思います。Pyhonではそれは不要です。ただ型が無い訳ではありません。```type(var)```という型を調べる関数がありますが、試しに先ほどの例の型を見てみましょう。


In [ ]:
print(type(name))
print(type(1))
print(type(1.0))
print(type(1j))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'complex'>


**name**はきちんと**str**つまり**String型**だと出てきました。整数は**int**(Integer)、小数は**float**、複素数は**complex**となりました。このように、Pythonでは変数の型は自動的に決定されます。

この方法論は『弱い型付け』とも呼ばれ、他にもRubyやJavaScript、PHP、Perl等が当てはまります。一方でJavaやC等は変数定義の時点で明示的に型を示す必要があり『強い型付け』と分類されます。

### 💮変数名をどうするか ###

皆さんは、変数名の命名をどうしていますか？

例えば年齢を入れるから**age**という変数名にするとか、カウンターを表す変数だから、頭文字をとって**c**とする等としていると思います。変数名の命名方法にはいくつか流派がありますが、まずはPythonとしてのルールを見てみましょう。

以下のような変数名は許されると思いますか？

In [ ]:
年齢 = 22
print(年齢)

22


なんと、これは実行が成功します。実は変数名等に日本語を使う事が出来ます。次はどうでしょうか？

In [ ]:
㍍ = 100
print(㍍)

SyntaxError: ignored

残念ながらこれはダメでした。ここら辺のルールは複雑なので割愛しますが、皆さんがすでに習っているJavaも日本語の変数名が付けられます。

日本語話者以外にプログラムを理解させたくない場合には便利かもしれませんが、それ以外に利点がないので、辞めて置く方が無難です。

それ以外にも、変数名にはいくつかPythonの文法上の制約があります。例えば数字で始まる変数名は使えません。

In [ ]:
5gatsu = 'May'

SyntaxError: ignored

**_**(アンダーバー)以外の記号は使えません。

In [ ]:
age_of_customer = 22
age-of-customer = 22

SyntaxError: ignored

言語仕様として予約されている語は変数名使えません

In [ ]:
True = 123

SyntaxError: ignored

その他、**False**、**None**や、今後説明する制御構文に使われる**if**や**for**等も変数名にする事が出来ません。

### 💮変数名のお作法 ###

変数名は**a**でも**b**でも**c**でも良いのですが、他人や一週間後の自分が読む事を考えると、**その変数が何であるのか**がきちんと分かる名前にする事が良いとされています。ただ、分かりやすい名前を考えれば考えるほど、数単語からなる変数名を付けたくなります。例えば学籍番号を管理するために**Student id number**という変数を作りたい場合どうしましょうか。Pythonとしての制約は、**変数名の途中にスペースが含められない**という事だけです。

以下のような変数名はどうでしょうか？

In [ ]:
Studentidnumber = '12345678'

Pythonの文法としては問題無いので、実行可能です。ただ、人間的には非常に読みにくいと思います。そこで、「**読みやすい方法**」が**いくつか**慣習として確立しています。

**Upper Camel Case**

各単語の最初のアルファベットを大文字にしてくっつけたもの

```
StudentIdNumber
```

**Lower Camel Case**

Upper Camel Caseと同様だか一番最初の文字を小文字にするもの

```
studentIdNumber
```

**Kebab Case**

スペースの代わりに**-**(ハイフン)を用いるもの

```
student-id-number
```

**Sneak Case**

スペースの代わりに**_**(アンダーバー)を用いるもの
```
student_id_number
```


Pythonでは慣習として**変数名にはSneak Case**を使います。なお、今後学習しますが、関数名もSnake Case、クラス名はUpper Camell Case、クラスのメソッド名にはSnake Caseを用います。

## 定数 ##

Pythonには定数はありません。

Pythonには定数はありません。

Pythonには定数はありません。

変数は自由に上書きができます。一方で定数は上書きが出来ない変数です。cの場合は```const float pi = 3.14f;```のように定義しますし、JavaScriptでは```const pi = 3.14;```のように定義します。Javaの場合は```final float pi = 3.14```です。このように宣言された定数は、実行時に別の値を新たに代入する事はできずエラーになります。

JavaScriptではπは```Math.PI```という定数が予め定義されています。定数ですのでこれを更新はできません。ではPythonではどうでしょうか。Pythonでもmath.piとしてπを扱う事ができます。


In [2]:
import math
print(math.pi)
# 3.141592653589793が表示されるはず
# ゆとりをもって「円周率を3にします」
math.pi = 3  # 定数ならばここでエラーが出るはずですが、Pythonではでません
# ではmath.piの中身がどうなったか見てみましょう。
print(math.pi)

3
3


ちなみに上記のセルを二回目実行すると、一行目も3になってしまいます。このノートにおいては、ランタイムを再起動(上のメニューにあります)しない限り、```math.pi```は**3**のままですのでご注意ください。

## 🌀まとめ ##

この**ノートブック**(Colabで表示しているこのコンテンツはJupyter Notebook形式のファイルですので、こう呼びます)では、Pythonのプログラム中で現れる様々なデータ型の値とそれを変数へ代入する方法を学びました。

次はデータ構造について学びます。[講義サポートページ](https://github.com/YokoyamaLab/PythonBasics/)に戻り資料03に進んでください。